# name: Web Build + Deployment to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2
  # Removido o PROJECT_PATH, assumindo que o projeto Flutter está na raiz.
  # Se o seu projeto estiver em uma subpasta, reintroduza esta variável
  # e ajuste o valor.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Certifique-se de que a etapa de configuração do Python e de instalação das dependências
    # não precisa de um working-directory, a menos que seus arquivos de requisitos estejam
    # em uma pasta específica.
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true # Enable caching

    # Removido working-directory, assumindo que o comando pode ser executado na raiz do repositório
    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Run Flutter doctor
      run: flutter doctor
    
    - name: Build Flutter web app
      run: flutter build web --base-url /${GITHUB_REPOSITORY#*/} --route-url-strategy hash

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact
        path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
