name: Deploy Flet Web App to GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PYTHON_VERSION: 3.12.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "ID=${{ secrets.ID }}" >> .env
        echo "SECRET_ID=${{ secrets.SECRET_ID }}" >> .env
        echo "REDIRECT_URL=${{ secrets.REDIRECT_URL }}" >> .env
        echo "USUARIO=${{ secrets.USUARIO }}" >> .env
        echo "SENHADB=${{ secrets.SENHADB }}" >> .env
        echo "DB=${{ secrets.DB }}" >> .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env

    - name: Build Flet web app
      run: flet build web --base-url /${GITHUB_REPOSITORY#*/} --route-url-strategy hash

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact
        path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
